apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlq-frontend
  namespace: nlq-system
  labels:
    app: nlq-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nlq-frontend
  template:
    metadata:
      labels:
        app: nlq-frontend
    spec:
      containers:
      - name: nlq-frontend
        image: nlq-frontend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: nlq-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nlq-frontend-service
  namespace: nlq-system
spec:
  selector:
    app: nlq-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nlq-frontend-hpa
  namespace: nlq-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nlq-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Min
