apiVersion: v1
kind: Secret
metadata:
  name: nlq-secrets
  namespace: nlq-system
type: Opaque
data:
  # Database password (base64 encoded)
  DB_PASSWORD: U3Ryb25nUGFzc3dvcmQxMjMh

  # Vector DB password (same as above, or separate if you want)
  VECTOR_DB_PASSWORD: U3Ryb25nUGFzc3dvcmQxMjMh

  # JWT secret key for auth (base64 encode your real secret string)
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2hlcmU=

  # Gemini API key (base64 encode your real key)
  GEMINI_API_KEY: Z2VtaW5pX2FwaV9rZXlfaGVyZQ==
