apiVersion: v1
kind: Secret
metadata:
  name: nlq-secrets
  namespace: nlq-app
  labels:
    app: nlq
    component: secrets
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # Use: echo -n "your_value" | base64
  DB_USER: bmxxX3VzZXI=  # nlq_user
  DB_PASSWORD: eW91cl9wYXNzd29yZF9oZXJl  # your_password_here
  VECTOR_DB_USER: bmxxX3VzZXI=  # nlq_user
  VECTOR_DB_PASSWORD: eW91cl9wYXNzd29yZF9oZXJl  # your_password_here
  GEMINI_API_KEY: eW91cl9nZW1pbmlfYXBpX2tleV9oZXJl  # your_gemini_api_key_here
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2hlcmU=  # your_jwt_secret_here
